version: '3.8'

services:
  db:
    image: postgres:15
    container_name: prode-db
    restart: always
    environment:
      POSTGRES_USER: prode_user
      POSTGRES_PASSWORD: prode_password
      POSTGRES_DB: prode_liga
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: prode-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@prode.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
