name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Angular
        run: npm run build

      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist/prode-liga-argentina